site_name: Zebrunner
repo_url: https://github.com/zebrunner/documentation
repo_name: Zebrunner

# Page tree
nav:
  - Overview: index.md
  - Getting started:
    - Registration: registration.md
    - Components overview: components_overview.md
  - User guide:
    - User profile: guide/user_profile.md
    - Dashboards: guide/dashboards.md
    - Widgets: guide/widgets.md
    - Projects: guide/projects.md
    - Test runs: guide/test_runs.md
    - Test sessions: guide/test_sessions.md
    - User management: guide/user_management.md
    - Integrations: guide/integrations.md
extra_css:
    - css/extra.css
markdown_extensions:
  - toc:
      toc_depth: 1-1
theme:
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.svg'
  font:
    text: Open Sans
  features:
    - navigation.expand
    - tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
