site_name: Zebrunner
repo_url: https://github.com/zebrunner/documentation
repo_name: Zebrunner

# Page tree
nav:
  - Overview: index.md
  - Getting started:
    - Registration: registration.md
    - Components overview: components_overview.md
  - Agents:
    - Java:
      - TestNG agent: agents/java/testng.md
      - JUnit agent: agents/java/junit.md
      - JUnit5 agent: agents/java/junit5.md
      - Advanced reporting: agents/java/advanced.md
    - JavaScript:
      - Jest: agents/javascript/jest.md
      - Jasmine: agents/javascript/jasmine.md
    - Python:
      - Pytest: agents/python/pytest.md
    - Ruby:
      - Rspec: agents/ruby/rspec.md
  - User guide:
    - User profile: guide/user_profile.md
    - Dashboards: guide/dashboards.md
    - Widgets: guide/widgets.md
    - Projects: guide/projects.md
    - Test runs: guide/test_runs.md
    - Test sessions: guide/test_sessions.md
    - User management: guide/user_management.md
    - Integrations: guide/integrations.md
extra_css:
    - css/extra.css
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: true
theme:
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.svg'
  font:
    text: Roboto
  features:
    - tabs
  palette:
    primary: black
